insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Comoda', 0.53, 0.70);
insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Mesa de luz', 0.53, 0.60);
insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Respaldo', 1.40, 1.20);
insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Zapatero', 0.53, 1.10);
insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Placard', 1.80, 1.80);
insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Chifonier', 1.00, 1.02);
insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Cama', 1.41, 1.41);
insert into mueble (categoria, nombre, ancho, largo) values ('Dormitorio', 'Cucheta', 1.20, 1.70);
insert into mueble (categoria, nombre, ancho, largo) values ('Comedor', 'Mesa', 1.40, 1.40);
insert into mueble (categoria, nombre, ancho, largo) values ('Comedor', 'Banqueta', 0.33, 0.75);
insert into mueble (categoria, nombre, ancho, largo) values ('Comedor', 'Silla', 0.43, 0.75);
insert into mueble (categoria, nombre, ancho, largo) values ('Comedor', 'Bahiut', 1.29, 0.90);
insert into mueble (categoria, nombre, ancho, largo) values ('Comedor', 'Modular', 1.83, 1.41);
insert into mueble (categoria, nombre, ancho, largo) values ('Cocina', 'Bajo mesada', 1.60, 0.80);
insert into mueble (categoria, nombre, ancho, largo) values ('Cocina', 'Alacena', 1.60, 0.80);
insert into mueble (categoria, nombre, ancho, largo) values ('Cocina', 'Mesada', 1.20, 0.15);
insert into mueble (categoria, nombre, ancho, largo) values ('Living', 'Mesa TV', 1.40, 0.91);
insert into mueble (categoria, nombre, ancho, largo) values ('Living', 'Divan', 1.00, 0.90);
insert into mueble (categoria, nombre, ancho, largo) values ('Living', 'Futon', 1.20, 0.90);
insert into mueble (categoria, nombre, ancho, largo) values ('Living', 'Mecedora', 1.00, 0.93);
insert into mueble (categoria, nombre, ancho, largo) values ('Living', 'Sillon', 1.60, 0.93);
insert into mueble (categoria, nombre, ancho, largo) values ('Oficina', 'Biblioteca', 0.80, 1.43);
insert into mueble (categoria, nombre, ancho, largo) values ('Oficina', 'Escritorio', 1.20, 0.75);